elasticsearch:
  build: elasticsearch/
  volumes:
    - $PWD/esdata:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"

kibana:
  image: kibana:4.5
  ports:
    - "5601:5601"
  links:
    - elasticsearch:elasticsearch

